### PR TITLE
feat: #405 activate page

### PR DESCRIPTION
**Pull request by Wongcheukwai**
adding the page.tsx for the activation email function. It's weird there are two commits.

### CODE REVIEW

**Comment by Yingxue0323** [comment]
Please merge two of your commits into one

**Comment by Wongcheukwai** [comment]
> Please merge two of your commits into one

done

**Review by wjtwzgl12 — COMMENTED** [review]
<div className="box" style={{ margin: '0 auto', maxWidth: '800px' }}>
The inline styles in this part are redundant with the styles defined in the CSS file. You can remove the inline styles and keep the CSS file styles.

**Comment by Wongcheukwai** [comment]
> The inline styles in this part are redundant with the styles defined in the CSS file. You can remove the inline styles and keep the CSS file styles.

done, thank you.

**Pull request merged**
